site_name: 'website-1'
site_description: 'Main documentation for the website-1'
repo_url: https://github.com/iagouvea/website-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'